#!/usr/bin/env bash

eval $(docker-machine env -u)

mkdir -p /my/home/goland

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -e GOPATH=${HOME}/go \
    --user=`id -u`:`id -g` \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix${DISPLAY} \
    --init \
    -v /my/home/goland:${HOME} \
    -v ${HOME}/go:${HOME}/go \
    --net none \
    --security-opt=seccomp:unconfined \
    --cpus=2 \
    goland:local
