#!/usr/bin/env bash

set -e

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user=`id -u`:`id -g` \
    --init \
    --workdir=${PWD} \
    -v ${PWD}:${PWD} \
    --entrypoint react-native-git-upgrade \
    metalguardian/react-native-git-upgrade \
    "$@"
