#!/usr/bin/env bash

set -e

mkdir -p ${HOME}/.ngrok2

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user=`id -u`:`id -g` \
    --net=host \
    --init \
    metalguardian/ngrok \
    "$@"
