#!/usr/bin/env bash

eval $(docker-machine env -u)

mkdir -p /my/home/gog

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user=`id -u`:`id -g` \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix${DISPLAY} \
    --init \
    --device /dev/snd \
    --device /dev/dri \
    --group-add audio \
    --group-add video \
    -v /my/home/gog:${HOME} \
    -v /files/games:/games \
    --net none \
    --security-opt=seccomp:unconfined \
    --cpus=2 \
    gog:local

    #agowa338/lutris