#!/usr/bin/env bash

set -e

mkdir -p \
    ${HOME}/.cache/yarn \
    ${HOME}/.yarn \
    ${HOME}/.config/yarn
touch ${HOME}/.yarnrc
touch ${HOME}/.npmrc

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user=`id -u`:`id -g` \
    --net=host \
    --init \
    --workdir=${PWD} \
    -v ${PWD}:${PWD} \
    -v ${HOME}/.cache/yarn:${HOME}/.cache/yarn \
    -v ${HOME}/.yarn:${HOME}/.yarn \
    -v ${HOME}/.yarnrc:${HOME}/.yarnrc \
    -v ${HOME}/.npmrc:${HOME}/.npmrc \
    -v ${HOME}/.config/yarn:${HOME}/.config/yarn \
    --entrypoint create-react-app \
    node:local \
    "$@"
