#!/usr/bin/env bash

set -e

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user=`id -u`:`id -g` \
    --net=host \
    --init \
    --workdir=${PWD} \
    -v ${PWD}:${PWD} \
    --entrypoint node \
    node:local \
    "$@"
