#!/usr/bin/env bash

set -e

mkdir -p \
    ${HOME}/.cache/yarn \
    ${HOME}/.yarn
touch ${HOME}/.yarnrc

docker run --rm -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --user=`id -u`:`id -g` \
    --net=host \
    --init \
    --workdir=${PWD} \
    -v ${PWD}:${PWD} \
    -v ${HOME}/.cache/yarn:${HOME}/.cache/yarn \
    -v ${HOME}/.yarn:${HOME}/.yarn \
    -v ${HOME}/.yarnrc:${HOME}/.yarnrc \
    --entrypoint yarn \
    metalguardian/node \
    "$@"
